### ISSUE TITLE
version miss match 

### ISSUE THREAD

**Issue by alokssingh** [FlashTek/keras-utility-layer-collection#5]
I am try to use 
    encoder = GRU(embedding_size, return_sequences=True, return_state=True, recurrent_dropout=0.1)
    attented_encoder = ExternalAttentionRNNWrapper(encoder, return_attention=True)
but got error in wrapper class 
  super(ExternalAttentionRNNWrapper, self).__init__(layer, **kwargs)

  File "C:\Users\NITS\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 52, in __init__
    assert isinstance(layer, Layer)

AssertionError

print(type(encoder))
  keras.layers.recurrent.LSTM but in Wrapper

  **assert isinstance(layer, Layer)**   error
    self.layer = layer
    # Tracks mapping of Wrapper inputs to inner layer inputs. Useful when
    # the inner layer has update ops that depend on its inputs (as opposed
    # to the inputs to the Wrapper layer).
    self._input_map = {}
    super(Wrapper, self).__init__(**kwargs)

**Comment by srigithub99** [comment]
TypeError: object of type 'ExternalAttentionRNNWrapper' has no len()

This error occurs..

**Comment by alokssingh** [comment]
@srigithub99  I this is your coding problem i didn't any this kind of problem
